"""initinal migrate

Revision ID: d3efa4cd3170
Revises:
Create Date: 2025-01-03 13:06:49.168360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3efa4cd3170'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory',
                    sa.Column('product_id', sa.Integer(), nullable=False),
                    sa.Column('current_quantity',
                              sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('product_id')
                    )
    op.create_table('inventory_logs',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('product_id', sa.Integer(), nullable=False),
                    sa.Column('change_quantity', sa.Integer(), nullable=False),
                    sa.Column('change_date', sa.DateTime(), nullable=False),
                    sa.Column('reason', sa.String(length=255), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['product_id'], ['inventory.product_id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory_logs')
    op.drop_table('inventory')
    # ### end Alembic commands ###
